'use client';

import { FormEvent, useEffect, useState } from 'react';
import { ArrowUp, Check, Clipboard, Command, Gift, Menu, Music2, Pause, Play, Send, X } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import AnimatedSection from './AnimatedSection';

const links = [['Home', '#home'], ['Story', '#story'], ['Couple', '#couple'], ['Event', '#event'], ['Gallery', '#gallery'], ['RSVP', '#rsvp']];

export function Navigation() {
  const [open, setOpen] = useState(false);
  return <>
    <header className="fixed top-0 z-40 w-full border-b border-border bg-background/75 backdrop-blur-xl">
      <nav className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4" aria-label="Navigasi undangan">
        <a href="#home" className="font-serif text-lg text-gold-light">F <span className="text-gold">&amp;</span> L</a>
        <div className="hidden items-center gap-6 md:flex">{links.map(([label, href]) => <a key={href} className="text-[11px] font-mono tracking-wider text-muted transition hover:text-gold" href={href}>{label}</a>)}</div>
        <button className="rounded-md border border-border p-2 text-gold md:hidden" aria-label="Buka menu" onClick={() => setOpen(!open)}>{open ? <X size={17}/> : <Menu size={17}/>}</button>
      </nav>
    </header>
    <AnimatePresence>{open && <motion.div initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -12 }} className="fixed inset-x-4 top-[68px] z-50 rounded-xl border border-border-gold bg-surface p-3 shadow-2xl md:hidden">{links.map(([label, href]) => <a onClick={() => setOpen(false)} key={href} className="block rounded-lg px-4 py-3 font-mono text-sm text-muted hover:bg-gold/10 hover:text-gold" href={href}>{label}</a>)}</motion.div>}</AnimatePresence>
  </>;
}

export function Guestbook() {
  const [entries, setEntries] = useState([{ name: 'Keluarga & Sahabat', text: 'Semoga menjadi keluarga yang penuh kebahagiaan, cinta, dan keberkahan.' }]);
  const [name, setName] = useState(''); const [text, setText] = useState('');
  function submit(e: FormEvent) { e.preventDefault(); if (!name.trim() || !text.trim()) return; setEntries([{ name: name.trim(), text: text.trim() }, ...entries]); setName(''); setText(''); }
  return <section id="guestbook" className="relative px-4 py-20 md:py-28"><div className="absolute inset-0 bg-surface/40"/><div className="relative mx-auto max-w-4xl">
    <AnimatedSection className="mb-10 text-center"><p className="font-mono text-xs uppercase tracking-[.3em] text-dim">{'// guestbook'}</p><h2 className="mt-3 font-serif text-3xl text-gold-light md:text-5xl">Wishes committed with love</h2><p className="mx-auto mt-4 max-w-md text-sm text-muted">Tinggalkan doa terbaik untuk perjalanan baru kami.</p></AnimatedSection>
    <div className="grid gap-5 md:grid-cols-[1.05fr_.95fr]"><form onSubmit={submit} className="glass-gold rounded-2xl p-5"><label className="mb-4 block font-mono text-xs text-dim">Nama<input value={name} onChange={e=>setName(e.target.value)} required className="mt-2 w-full rounded-lg border border-border bg-card p-3 text-sm text-foreground outline-none focus:border-border-gold" /></label><label className="block font-mono text-xs text-dim">Ucapan<textarea value={text} onChange={e=>setText(e.target.value)} required rows={4} className="mt-2 w-full resize-none rounded-lg border border-border bg-card p-3 text-sm text-foreground outline-none focus:border-border-gold" /></label><button className="mt-4 inline-flex items-center gap-2 rounded-lg border border-border-gold px-4 py-3 font-mono text-xs text-gold hover:bg-gold/10"><Send size={14}/> Commit wish</button></form><div className="max-h-[340px] space-y-3 overflow-y-auto pr-1">{entries.map((entry, index) => <motion.article key={`${entry.name}-${index}`} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="rounded-xl border border-border bg-card/80 p-4"><p className="font-mono text-[10px] text-dim">commit #{String(entries.length-index).padStart(3, '0')}</p><h3 className="mt-1 font-serif text-lg text-gold-light">{entry.name}</h3><p className="mt-2 text-sm leading-relaxed text-muted">“{entry.text}”</p><p className="mt-3 font-mono text-[10px] text-[#28c840]">✓ committed</p></motion.article>)}</div></div>
  </div></section>;
}

export function DigitalGift() {
  const [copied, setCopied] = useState(false);
  async function copy() { await navigator.clipboard?.writeText('[NOMOR REKENING]'); setCopied(true); setTimeout(() => setCopied(false), 1800); }
  return <section className="relative px-4 py-20 md:py-28"><div className="relative mx-auto max-w-3xl"><AnimatedSection className="text-center"><Gift className="mx-auto text-gold"/><p className="mt-4 font-mono text-xs uppercase tracking-[.3em] text-dim">{'// digital gift'}</p><h2 className="mt-3 font-serif text-3xl text-gold-light md:text-5xl">A little token of love</h2><p className="mx-auto mt-4 max-w-lg text-sm leading-relaxed text-muted">Doa Anda adalah hadiah terindah. Bagi yang ingin mengirimkan tanda kasih, detail berikut dapat diisi kemudian.</p></AnimatedSection><AnimatedSection delay={.15} className="mx-auto mt-9 max-w-xl"><div className="glass-gold rounded-2xl p-6"><p className="font-mono text-xs text-dim">bank_account.json</p><div className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><p><span className="block font-mono text-[10px] text-dim">BANK</span><span className="text-gold-light">[NAMA BANK]</span></p><p><span className="block font-mono text-[10px] text-dim">ATAS NAMA</span><span className="text-gold-light">[NAMA PEMILIK]</span></p></div><div className="mt-5 flex items-center justify-between rounded-lg border border-border bg-card px-4 py-3"><span className="font-mono text-sm text-muted">[NOMOR REKENING]</span><button onClick={copy} className="inline-flex items-center gap-2 font-mono text-xs text-gold" aria-label="Salin nomor rekening">{copied ? <Check size={14}/> : <Clipboard size={14}/>} {copied ? 'Copied' : 'Copy'}</button></div><p className="mt-5 font-mono text-xs text-dim">E-Wallet: [NAMA E-WALLET / NOMOR]</p></div></AnimatedSection></div></section>;
}

export function MusicPlayer() { const [playing, setPlaying] = useState(false); return <button onClick={()=>setPlaying(!playing)} className="fixed bottom-5 right-5 z-30 inline-flex items-center gap-2 rounded-full border border-border-gold bg-background/85 px-4 py-3 font-mono text-xs text-gold shadow-xl backdrop-blur" aria-label="Kontrol musik placeholder">{playing ? <Pause size={14}/> : <Play size={14}/>} <Music2 size={14} className={playing ? 'animate-pulse':''}/><span>{playing ? 'Pause' : 'Music'}</span></button>; }

export function MiniTerminal() { const [open,setOpen]=useState(false); const [input,setInput]=useState(''); const [output,setOutput]=useState('Ketik help untuk melihat perintah.'); function run(e:FormEvent){e.preventDefault(); const replies:Record<string,string>={help:'Commands: help, love, story, date',love:'Status: FOREVER ❤️',story:'Dua perjalanan, satu destination.',date:'30.10.2031'}; setOutput(replies[input.toLowerCase()] ?? 'Command not found. Try: help'); setInput('');} return <div className="fixed bottom-5 left-5 z-30"><AnimatePresence>{open&&<motion.form initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:12}} onSubmit={run} className="mb-3 w-[min(300px,calc(100vw-40px))] rounded-xl border border-border-gold bg-card p-4 shadow-2xl"><p className="font-mono text-xs text-gold">$ {output}</p><label className="mt-3 flex font-mono text-sm text-muted">&gt;<input autoFocus value={input} onChange={e=>setInput(e.target.value)} className="ml-2 min-w-0 flex-1 bg-transparent outline-none" aria-label="Terminal command"/></label></motion.form>}</AnimatePresence><button onClick={()=>setOpen(!open)} className="rounded-full border border-border bg-background/85 p-3 text-gold backdrop-blur" aria-label="Buka terminal mini"><Command size={17}/></button></div>; }

export function FinalCommit() { return <footer className="border-t border-border px-4 py-20 text-center"><AnimatedSection><p className="font-mono text-xs text-dim">commit 30102031</p><h2 className="mt-3 font-serif text-3xl text-gold-light md:text-5xl">“Forever starts here.”</h2><p className="mt-5 font-mono text-sm text-muted">Muhammad Faturrahman Putra &amp; Laura Shakira Aisyah Putri</p><p className="mt-2 text-sm text-dim">30 Oktober 2031</p><pre className="mt-10 font-mono text-xs text-gold/60">while (love) {'{'}\n  together();\n{'}'}</pre><a href="#home" className="mt-8 inline-flex items-center gap-2 font-mono text-xs text-gold"><ArrowUp size={14}/> Back to top</a><p className="mt-8 text-xs text-dim">Built with love &amp; a little bit of code. © 2031</p></AnimatedSection></footer>; }

export function CustomCursor() {
  const [pos,setPos]=useState({x:-50,y:-50}); const [secret,setSecret]=useState(false);
  useEffect(()=>{const move=(e:MouseEvent)=>setPos({x:e.clientX,y:e.clientY}); const sequence=['ArrowUp','ArrowUp','ArrowDown','ArrowDown','ArrowLeft','ArrowRight','ArrowLeft','ArrowRight','b','a']; let keys:string[]=[]; const key=(e:KeyboardEvent)=>{keys=[...keys,e.key].slice(-10);if(keys.join('|')===sequence.join('|')){setSecret(true);setTimeout(()=>setSecret(false),3500)}}; window.addEventListener('mousemove',move);window.addEventListener('keydown',key);return()=>{window.removeEventListener('mousemove',move);window.removeEventListener('keydown',key)}},[]);
  return <>{secret && <motion.div initial={{opacity:0,scale:.9}} animate={{opacity:1,scale:1}} exit={{opacity:0}} className="fixed inset-0 z-[90] grid place-items-center bg-background/90 p-6 text-center backdrop-blur"><div className="rounded-2xl border border-border-gold bg-card p-10"><p className="font-mono text-xs tracking-[.3em] text-dim">ACCESS GRANTED</p><p className="mt-4 font-serif text-3xl text-gold-light">You found our secret.</p><p className="mt-3 text-4xl">❤️</p></div></motion.div>}<span aria-hidden className="pointer-events-none fixed z-[80] hidden h-7 w-7 -translate-x-1/2 -translate-y-1/2 rounded-full border border-gold/70 bg-gold/10 shadow-[0_0_18px_rgba(205,161,58,.35)] md:block" style={{left:pos.x,top:pos.y}}/></>;
}
